% FORCESNLPsolver - a fast interior point code generated by FORCES
%
%   OUTPUT = FORCESNLPsolver(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.xinit - column vector of length 12
%       PARAMS.x0 - column vector of length 1530
%       PARAMS.all_parameters - column vector of length 170
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.x01 - column vector of size 18
%       OUTPUT.x02 - column vector of size 18
%       OUTPUT.x03 - column vector of size 18
%       OUTPUT.x04 - column vector of size 18
%       OUTPUT.x05 - column vector of size 18
%       OUTPUT.x06 - column vector of size 18
%       OUTPUT.x07 - column vector of size 18
%       OUTPUT.x08 - column vector of size 18
%       OUTPUT.x09 - column vector of size 18
%       OUTPUT.x10 - column vector of size 18
%       OUTPUT.x11 - column vector of size 18
%       OUTPUT.x12 - column vector of size 18
%       OUTPUT.x13 - column vector of size 18
%       OUTPUT.x14 - column vector of size 18
%       OUTPUT.x15 - column vector of size 18
%       OUTPUT.x16 - column vector of size 18
%       OUTPUT.x17 - column vector of size 18
%       OUTPUT.x18 - column vector of size 18
%       OUTPUT.x19 - column vector of size 18
%       OUTPUT.x20 - column vector of size 18
%       OUTPUT.x21 - column vector of size 18
%       OUTPUT.x22 - column vector of size 18
%       OUTPUT.x23 - column vector of size 18
%       OUTPUT.x24 - column vector of size 18
%       OUTPUT.x25 - column vector of size 18
%       OUTPUT.x26 - column vector of size 18
%       OUTPUT.x27 - column vector of size 18
%       OUTPUT.x28 - column vector of size 18
%       OUTPUT.x29 - column vector of size 18
%       OUTPUT.x30 - column vector of size 18
%       OUTPUT.x31 - column vector of size 18
%       OUTPUT.x32 - column vector of size 18
%       OUTPUT.x33 - column vector of size 18
%       OUTPUT.x34 - column vector of size 18
%       OUTPUT.x35 - column vector of size 18
%       OUTPUT.x36 - column vector of size 18
%       OUTPUT.x37 - column vector of size 18
%       OUTPUT.x38 - column vector of size 18
%       OUTPUT.x39 - column vector of size 18
%       OUTPUT.x40 - column vector of size 18
%       OUTPUT.x41 - column vector of size 18
%       OUTPUT.x42 - column vector of size 18
%       OUTPUT.x43 - column vector of size 18
%       OUTPUT.x44 - column vector of size 18
%       OUTPUT.x45 - column vector of size 18
%       OUTPUT.x46 - column vector of size 18
%       OUTPUT.x47 - column vector of size 18
%       OUTPUT.x48 - column vector of size 18
%       OUTPUT.x49 - column vector of size 18
%       OUTPUT.x50 - column vector of size 18
%       OUTPUT.x51 - column vector of size 18
%       OUTPUT.x52 - column vector of size 18
%       OUTPUT.x53 - column vector of size 18
%       OUTPUT.x54 - column vector of size 18
%       OUTPUT.x55 - column vector of size 18
%       OUTPUT.x56 - column vector of size 18
%       OUTPUT.x57 - column vector of size 18
%       OUTPUT.x58 - column vector of size 18
%       OUTPUT.x59 - column vector of size 18
%       OUTPUT.x60 - column vector of size 18
%       OUTPUT.x61 - column vector of size 18
%       OUTPUT.x62 - column vector of size 18
%       OUTPUT.x63 - column vector of size 18
%       OUTPUT.x64 - column vector of size 18
%       OUTPUT.x65 - column vector of size 18
%       OUTPUT.x66 - column vector of size 18
%       OUTPUT.x67 - column vector of size 18
%       OUTPUT.x68 - column vector of size 18
%       OUTPUT.x69 - column vector of size 18
%       OUTPUT.x70 - column vector of size 18
%       OUTPUT.x71 - column vector of size 18
%       OUTPUT.x72 - column vector of size 18
%       OUTPUT.x73 - column vector of size 18
%       OUTPUT.x74 - column vector of size 18
%       OUTPUT.x75 - column vector of size 18
%       OUTPUT.x76 - column vector of size 18
%       OUTPUT.x77 - column vector of size 18
%       OUTPUT.x78 - column vector of size 18
%       OUTPUT.x79 - column vector of size 18
%       OUTPUT.x80 - column vector of size 18
%       OUTPUT.x81 - column vector of size 18
%       OUTPUT.x82 - column vector of size 18
%       OUTPUT.x83 - column vector of size 18
%       OUTPUT.x84 - column vector of size 18
%       OUTPUT.x85 - column vector of size 18
%
%   [OUTPUT, EXITFLAG] = FORCESNLPsolver(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = FORCESNLPsolver(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.mu        - duality measure
%       INFO.solvetime - Time needed for solve (wall clock time)
%       INFO.fevalstime - Time needed for solve (wall clock time)
%
% See also COPYING
