/* This function was automatically generated by CasADi */#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) FORCESNLPsolver_model_85_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef double
#define double double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* double */

#define PRINTF printf
double CASADI_PREFIX(sq)(double x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

double CASADI_PREFIX(sign)(double x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {2, 1, 0, 2, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[] = {1, 18, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const int CASADI_PREFIX(s4)[] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
#define s4 CASADI_PREFIX(s4)
static const int CASADI_PREFIX(s5)[] = {5, 18, 0, 0, 0, 0, 0, 0, 0, 3, 6, 8, 8, 10, 12, 12, 12, 14, 16, 16, 16, 0, 3, 4, 0, 3, 4, 3, 4, 1, 3, 1, 3, 2, 4, 2, 4};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
int FORCESNLPsolver_model_85(const double** arg, double** res) {
     double a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45,a46,a47,a48,a49,a50,a51,a52,a53,a54,a55,a56,a57,a58,a59,a60,a61;
         a0=arg[0] ? arg[0][6] : 0;
         a1=1.5000000000000000e+00;
  a1=(a0-a1);
         a2=sq(a1);
         a3=100.;
  a2=(a3*a2);
         a4=arg[0] ? arg[0][7] : 0;
         a5=sq(a4);
  a5=(a3*a5);
  a2=(a2+a5);
  if (res[0]!=0) res[0][0]=a2;
  a1=(a1+a1);
  a1=(a3*a1);
  if (res[1]!=0) res[1][0]=a1;
  a1=(a4+a4);
  a3=(a3*a1);
  if (res[1]!=0) res[1][1]=a3;
  a3=sq(a0);
  a1=sq(a4);
  a3=(a3+a1);
  if (res[2]!=0) res[2][0]=a3;
  a3=arg[0] ? arg[0][10] : 0;
  a1=sq(a3);
  a2=arg[0] ? arg[0][11] : 0;
  a5=sq(a2);
  a1=(a1+a5);
  a5=2.2500000000000000e+00;
  a1=(a1-a5);
  if (res[2]!=0) res[2][1]=a1;
  a1=arg[0] ? arg[0][14] : 0;
         a6=sq(a1);
         a7=arg[0] ? arg[0][15] : 0;
         a8=sq(a7);
  a6=(a6+a8);
  a8=4.;
  a6=(a6-a8);
  if (res[2]!=0) res[2][2]=a6;
  a6=(a0-a3);
         a9=-2.;
         a10=(a9*a3);
         a11=sq(a3);
  a11=(a5-a11);
         a12=2.;
  a11=(a12*a11);
  a10=(a10/a11);
         a13=1.;
         a14=atan2(a10,a13);
         a15=cos(a14);
         a16=(a15*a6);
         a17=(a4-a2);
         a18=(a9*a3);
         a19=sq(a3);
  a19=(a5-a19);
  a19=(a12*a19);
  a18=(a18/a19);
         a20=atan2(a18,a13);
         a21=sin(a20);
         a22=(a21*a17);
  a16=(a16+a22);
  a22=sq(a16);
         a23=2.9999999999999999e-01;
         a24=arg[0] ? arg[0][8] : 0;
         a25=(a23+a24);
         a26=sq(a25);
  a22=(a22/a26);
         a27=(a0-a3);
         a28=(a9*a3);
         a29=sq(a3);
  a29=(a5-a29);
  a29=(a12*a29);
  a28=(a28/a29);
         a30=atan2(a28,a13);
         a31=sin(a30);
         a32=(a31*a27);
         a33=(a4-a2);
         a34=(a9*a3);
         a35=sq(a3);
  a5=(a5-a35);
  a5=(a12*a5);
  a34=(a34/a5);
  a35=atan2(a34,a13);
         a36=cos(a35);
         a37=(a36*a33);
  a32=(a32-a37);
  a37=sq(a32);
         a38=2.5000000000000000e-01;
  a37=(a37/a38);
  a37=(a22+a37);
  if (res[2]!=0) res[2][3]=a37;
  a37=(a0-a1);
         a39=(a9*a1);
         a40=sq(a1);
  a40=(a8-a40);
  a40=(a12*a40);
  a39=(a39/a40);
         a41=atan2(a39,a13);
         a42=cos(a41);
         a43=(a42*a37);
         a44=(a4-a7);
         a45=(a9*a1);
         a46=sq(a1);
  a46=(a8-a46);
  a46=(a12*a46);
  a45=(a45/a46);
         a47=atan2(a45,a13);
         a48=sin(a47);
         a49=(a48*a44);
  a43=(a43+a49);
  a49=sq(a43);
  a23=(a23+a24);
  a24=sq(a23);
  a49=(a49/a24);
         a50=(a0-a1);
         a51=(a9*a1);
         a52=sq(a1);
  a52=(a8-a52);
  a52=(a12*a52);
  a51=(a51/a52);
         a53=atan2(a51,a13);
         a54=sin(a53);
         a55=(a54*a50);
         a56=(a4-a7);
         a57=(a9*a1);
         a58=sq(a1);
  a58=(a8-a58);
  a58=(a12*a58);
  a57=(a57/a58);
         a59=atan2(a57,a13);
         a60=cos(a59);
         a61=(a60*a56);
  a55=(a55-a61);
  a61=sq(a55);
  a61=(a61/a38);
  a61=(a49+a61);
  if (res[2]!=0) res[2][4]=a61;
  a0=(a0+a0);
  if (res[3]!=0) res[3][0]=a0;
  a16=(a16+a16);
  a0=(a16*a15);
  a0=(a0/a26);
  a32=(a32+a32);
  a61=(a32*a31);
  a61=(a8*a61);
  a0=(a0+a61);
  if (res[3]!=0) res[3][1]=a0;
  a43=(a43+a43);
  a0=(a43*a42);
  a0=(a0/a24);
  a55=(a55+a55);
  a61=(a55*a54);
  a61=(a8*a61);
  a0=(a0+a61);
  if (res[3]!=0) res[3][2]=a0;
  a4=(a4+a4);
  if (res[3]!=0) res[3][3]=a4;
  a4=(a16*a21);
  a4=(a4/a26);
  a0=(a32*a36);
  a0=(a8*a0);
  a4=(a4-a0);
  if (res[3]!=0) res[3][4]=a4;
  a4=(a43*a48);
  a4=(a4/a24);
  a0=(a55*a60);
  a0=(a8*a0);
  a4=(a4-a0);
  if (res[3]!=0) res[3][5]=a4;
  a22=(a22/a26);
  a25=(a25+a25);
  a22=(a22*a25);
  a22=(-a22);
  if (res[3]!=0) res[3][6]=a22;
  a49=(a49/a24);
  a23=(a23+a23);
  a49=(a49*a23);
  a49=(-a49);
  if (res[3]!=0) res[3][7]=a49;
  a49=(a3+a3);
  if (res[3]!=0) res[3][8]=a49;
  a49=(a9/a19);
  a19=(a18/a19);
  a23=(a3+a3);
  a23=(a12*a23);
  a19=(a19*a23);
  a49=(a49+a19);
  a18=sq(a18);
  a18=(a18+a13);
  a49=(a49/a18);
  a20=cos(a20);
  a20=(a20*a49);
  a17=(a17*a20);
  a20=(a9/a11);
  a11=(a10/a11);
  a49=(a3+a3);
  a49=(a12*a49);
  a11=(a11*a49);
  a20=(a20+a11);
  a10=sq(a10);
  a10=(a10+a13);
  a20=(a20/a10);
  a14=sin(a14);
  a14=(a14*a20);
  a6=(a6*a14);
  a6=(a6+a15);
  a17=(a17-a6);
  a17=(a16*a17);
  a17=(a17/a26);
  a6=(a9/a29);
  a29=(a28/a29);
  a15=(a3+a3);
  a15=(a12*a15);
  a29=(a29*a15);
  a6=(a6+a29);
  a28=sq(a28);
  a28=(a28+a13);
  a6=(a6/a28);
  a30=cos(a30);
  a30=(a30*a6);
  a27=(a27*a30);
  a27=(a27-a31);
  a31=(a9/a5);
  a5=(a34/a5);
  a3=(a3+a3);
  a3=(a12*a3);
  a5=(a5*a3);
  a31=(a31+a5);
  a34=sq(a34);
  a34=(a34+a13);
  a31=(a31/a34);
  a35=sin(a35);
  a35=(a35*a31);
  a33=(a33*a35);
  a27=(a27+a33);
  a27=(a32*a27);
  a27=(a8*a27);
  a17=(a17+a27);
  if (res[3]!=0) res[3][9]=a17;
  a2=(a2+a2);
  if (res[3]!=0) res[3][10]=a2;
  a32=(a32*a36);
  a32=(a8*a32);
  a16=(a16*a21);
  a16=(a16/a26);
  a32=(a32-a16);
  if (res[3]!=0) res[3][11]=a32;
  a32=(a1+a1);
  if (res[3]!=0) res[3][12]=a32;
  a32=(a9/a46);
  a46=(a45/a46);
  a16=(a1+a1);
  a16=(a12*a16);
  a46=(a46*a16);
  a32=(a32+a46);
  a45=sq(a45);
  a45=(a45+a13);
  a32=(a32/a45);
  a47=cos(a47);
  a47=(a47*a32);
  a44=(a44*a47);
  a47=(a9/a40);
  a40=(a39/a40);
  a32=(a1+a1);
  a32=(a12*a32);
  a40=(a40*a32);
  a47=(a47+a40);
  a39=sq(a39);
  a39=(a39+a13);
  a47=(a47/a39);
  a41=sin(a41);
  a41=(a41*a47);
  a37=(a37*a41);
  a37=(a37+a42);
  a44=(a44-a37);
  a44=(a43*a44);
  a44=(a44/a24);
  a37=(a9/a52);
  a52=(a51/a52);
  a42=(a1+a1);
  a42=(a12*a42);
  a52=(a52*a42);
  a37=(a37+a52);
  a51=sq(a51);
  a51=(a51+a13);
  a37=(a37/a51);
  a53=cos(a53);
  a53=(a53*a37);
  a50=(a50*a53);
  a50=(a50-a54);
  a9=(a9/a58);
  a58=(a57/a58);
  a1=(a1+a1);
  a12=(a12*a1);
  a58=(a58*a12);
  a9=(a9+a58);
  a57=sq(a57);
  a57=(a57+a13);
  a9=(a9/a57);
  a59=sin(a59);
  a59=(a59*a9);
  a56=(a56*a59);
  a50=(a50+a56);
  a50=(a55*a50);
  a50=(a8*a50);
  a44=(a44+a50);
  if (res[3]!=0) res[3][13]=a44;
  a7=(a7+a7);
  if (res[3]!=0) res[3][14]=a7;
  a55=(a55*a60);
  a8=(a8*a55);
  a43=(a43*a48);
  a43=(a43/a24);
  a8=(a8-a43);
  if (res[3]!=0) res[3][15]=a8;
  return 0;
}

int FORCESNLPsolver_model_85_init(int *f_type, int *n_in, int *n_out, int *sz_arg, int* sz_res) {
  *f_type = 1;
  *n_in = 2;
  *n_out = 4;
  *sz_arg = 2;
  *sz_res = 4;
  return 0;
}

int FORCESNLPsolver_model_85_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row) {
  const int* s;
  switch (i) {
    case 0:
      s = s0; break;
    case 1:
      s = s1; break;
    case 2:
      s = s2; break;
    case 3:
      s = s3; break;
    case 4:
      s = s4; break;
    case 5:
      s = s5; break;
    default:
      return 1;
  }

  *nrow = s[0];
  *ncol = s[1];
  *colind = s + 2;
  *row = s + 2 + (*ncol + 1);
  return 0;
}

int FORCESNLPsolver_model_85_work(int *sz_iw, int *sz_w) {
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 62;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
